#!/usr/bin/env emacs --script
;;; run-tests.el --- Run all superchat tests -*- lexical-binding: t; -*-

;;; Commentary:

;; This script runs the canonical Superchat test suite:
;;   - Agentic Skills (superchat-skills.el / superchat-executor.el)
;;   - Skills integration
;;   - llm.el backend (superchat-backend-show, dispatchers, tool registry)
;;
;; Usage: emacs -Q -l test/run-tests.el

;;; Code:

(require 'ert)

;; Prefer edited sources over stale local .elc files.  This repository has no
;; build step, so generated bytecode should never mask the code under test.
(setq load-prefer-newer t)

;; Setup load path
(add-to-list 'load-path (expand-file-name ".." (file-name-directory load-file-name)))

;; Load modules
(require 'superchat-skills)
(require 'superchat-executor)
;; `superchat' must load before test-llm-backend.el so the defcustoms,
;; dispatchers and the `superchat-backend-show' / tool registry are
;; defined for the tests to monkey-patch.
(require 'superchat)

;; Load test files
(load-file (expand-file-name "test-skills.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-skills-integration.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-llm-backend.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-rewrite.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-context.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-ecosystem.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-native-ui.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-agent-loop.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-compact.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-tape-view.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-subagent.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-workflow.el" (file-name-directory load-file-name)))

;; Run tests
(message "\n=== Running Superchat Tests ===\n")

;; Match every loaded deftest.  Test names use mixed prefixes
;; (`test-', `native-ui/', `rewrite/', `context/', `ecosystem/'),
;; so an `^test-' selector would silently skip the latter four.
(ert-run-tests-batch-and-exit t)

;;; run-tests.el ends here
