#!/usr/bin/env emacs --script
;;; run-tests.el --- Run all superchat tests -*- lexical-binding: t; -*-

;;; Commentary:

;; This script runs the canonical Superchat test suite:
;;   - Agentic Skills (superchat-skills.el / superchat-executor.el)
;;   - Skills integration
;;   - llm.el backend (superchat-backend-show, dispatchers, tool registry)
;;
;; Usage: emacs -Q -l test/run-tests.el

;;; Code:

(require 'ert)

;; Prefer edited sources over stale local .elc files.  This repository has no
;; build step, so generated bytecode should never mask the code under test.
(setq load-prefer-newer t)

;; Setup load path
(defconst superchat-test--root
  (expand-file-name ".." (file-name-directory load-file-name)))
(add-to-list 'load-path superchat-test--root)

;; Load the generated-UI gate explicitly.  `superchat' also reaches it via
;; `superchat-tools', but keeping the direct dependency here makes this
;; runner self-describing and robust when a test is loaded in isolation.
(load-file (expand-file-name "superchat-genui.el" superchat-test--root))

;; Load modules
(require 'superchat-skills)
(require 'superchat-executor)
;; `superchat' must load before test-llm-backend.el so the defcustoms,
;; dispatchers and the `superchat-backend-show' / tool registry are
;; defined for the tests to monkey-patch.
(require 'superchat)

;; Sandbox all data-directory writes.  Without this, tests that touch the
;; default `*superchat*' buffer leave content behind, and the
;; `kill-emacs-hook' session cache then writes test junk into the USER'S
;; real data directory at batch exit (observed: mock tool renders landing
;; in ~/.emacs.d/superchat/session-cache.org, which the next interactive
;; startup would feed to the memory summarizer).
(setq superchat-data-directory
      (make-temp-file "superchat-test-data" t))

;; Load test files
(load-file (expand-file-name "test-skills.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-skills-integration.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-skills-roundtrip.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-preset-contract.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-llm-backend.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-rewrite.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-context.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-ecosystem.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-native-ui.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-agent-loop.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-compact.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-tape-view.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-subagent.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-agents-panel.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-genui.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-genui-render.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-workflow.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-workspace.el" (file-name-directory load-file-name)))
(load-file (expand-file-name "test-synthesis.el" (file-name-directory load-file-name)))

;; Run tests
(message "\n=== Running Superchat Tests ===\n")

;; Match every loaded deftest.  Test names use mixed prefixes
;; (`test-', `native-ui/', `rewrite/', `context/', `ecosystem/'),
;; so an `^test-' selector would silently skip the latter four.
(ert-run-tests-batch-and-exit t)

;;; run-tests.el ends here
